### ISSUE TITLE
Add TL-280 Configuration Steps

### ISSUE THREAD

**Issue by mtwo** [BrianHumlicek/DSC-TLink#5]
@BrianHumlicek @pcanto-hopeit @Villhahallon

I've installed a TL-280 into my system and followed the configuration steps outlined in the manual, including setting the ethernet 1 IP address to my development machine. It's grabbing an IP address from my network but I can't see any traffic coming from it beyond that.

Are you able to note down the configuration steps that you used on the panel so that I can (a) reproduce them and assist with development, and (b) I can make a PR to the repo that others can follow?

**Comment by mtwo** [comment]
Nevermind, I got this working after following the Control4 setup steps rather than the TL-280 setup manual

**Comment by BrianHumlicek** [comment]
I’m glad you got it working.  Adding configuration steps is on my todo list.  I spent some time playing with settings to figure out what is necessary, I just need to document it.

**Comment by mtwo** [comment]
Here were my setup steps:

1. Connect the TL-280 to the alarm panel with the included wire, and connect it to an ethernet cable.
2. Enter [*][8][installer code][851] on an alarm keypad to access configuration sections for the communicator. All following instructions will enter section numbers for each configuration option.
3. Ensure that [021] is not set to 000000 or FFFFFF.
4. Ensure that [101] is not set to 000000 or FFFFFF.
5. Set [103] to the IP address of the system that the alarm will communicating with.
6. Set [425] to 3 and 5.
7. Set [426] to 3.
8. Set [428] to the IP address of the system that the alarm will communicating with.
9. Set [429] to 0C00.
10. Set [711] to 00000078.

@BrianHumlicek I'll create a PR to the Readme with these. I'm using DHCP and I'm guessing that most other people will be (?), so I skipped the static IP, subnet, and gateway configuration steps.
